[package]
name = "playground"
version = "1.0.0"
authors = []

[addresses]
playground_addr = "_"
# ANS address on testnet is 0x5f8fd2347449685cf41d4db97926ec3a096eaf381332be4f1318ad4d16a8497c
# on mainnet is 0x867ed1f6bf916171b1de3ee92849b8978b7d1b9e0a8cc982a3d19d535dfd9c0c
aptos_names = "_"
aptos_names_admin = "_"
aptos_names_funds = "_"
router_signer = "_"
aptos_names_v2_1 = "_"
router = "_"

#[dev-addresses]
#playground_addr = "0x999"
#aptos_names = "0x998"
#aptos_names_admin = "0x997"
#aptos_names_funds = "0x996"
#router_signer = "0x995"
#aptos_names_v2_1 = "0x994"
#router = "0x993"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects"}
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token"}
router = { git = "https://github.com/aptos-labs/aptos-names-contracts.git", rev = "main", subdir = "router"}

[dev-dependencies]
